/**
 * useFleetHistory — loads full batch history + live socket ticks for all running
 * machines. Returns two series arrays (temperature + vacuum pressure) for the
 * FleetLineChart component on the Overview page.
 *
 * Design decisions:
 *  - Opens 8 socket connections using the same forceNew pattern as useAllFryers.
 *    This is intentional: socket rooms are fryer-scoped and the server emits on
 *    noi_chien_N_data / noi_chien_N_stop rooms. Sharing sockets across hooks would
 *    require a shared context — the duplication (8 extra connections) is acceptable
 *    for a local LAN dashboard with 8 machines.
 *  - Capped at MAX_POINTS per machine with even downsampling, preserving both
 *    the beginning of stage 1 and the end of stage 4.
 *  - Live points appended only when the new phut is at least MIN_PHUT_GAP minutes
 *    ahead of the last recorded point, avoiding point-density explosion.
 *  - X values use only timestamps generated by the backend. The Docker backend
 *    and browser can run in different time zones, so Date.now() must not be mixed
 *    with the backend's locale timestamp strings.
 *  - The last completed batch remains visible until stage 1 of the next batch.
 */
import { useEffect, useRef, useState } from 'react';
import { io, Socket } from 'socket.io-client';
import { getNoiChien, getNoiChienDetail } from '../api';
import { parseTs } from './timeUtils';
import type {
  StagePayload,
  NoiChienDataPayload,
  BienDuLieuEntry,
  BatchDocument,
} from '../types';

/** A single chart data point */
export interface ChartPoint {
  /** Minutes elapsed since batch start (X axis) */
  phut: number;
  /** Sensor value (Y axis) */
  value: number;
  /** Stage 1-4 (shown in tooltip only) */
  stage: 1 | 2 | 3 | 4;
}

/** Series for one machine */
export interface MachineSeries {
  /** Fryer number 1-8 */
  n: number;
  /** Hex color for this series — chart series palette, NOT semantic val.* colors */
  color: string;
  points: ChartPoint[];
}

/**
 * Chart series palette — 8 visually distinct colors, harmonious with the brand
 * blue (#2196f3). Chosen for max perceptual distance on light background.
 * NOTE: These are chart series colors only; semantic val.* colors (from ui-dna)
 * apply to numeric readouts, not to multi-series charts.
 */
export const FRYER_CHART_COLORS: Record<number, string> = {
  1: '#2196f3', // brand blue
  2: '#e53935', // vivid red
  3: '#43a047', // medium green
  4: '#fb8c00', // amber
  5: '#8e24aa', // purple
  6: '#00acc1', // cyan/teal
  7: '#f06292', // pink
  8: '#6d4c41', // brown
};

const MAX_POINTS = 300;
const MIN_PHUT_GAP = 0.4; // ~24 seconds minimum gap between live appended points

function capPoints(points: ChartPoint[]): ChartPoint[] {
  if (points.length <= MAX_POINTS) return points;

  return Array.from({ length: MAX_POINTS }, (_, i) => {
    const index = Math.round((i * (points.length - 1)) / (MAX_POINTS - 1));
    return points[index];
  });
}

/** Is a bien_du_lieu entry an init/zero record (skip it)? */
function isInitEntry(entry: BienDuLieuEntry): boolean {
  return (entry.nhiet_do ?? 0) === 0 && (entry.ap_suat_chan_khong ?? 0) === 0;
}

/** Build ChartPoint[] from a giai_doan bien_du_lieu array */
function buildPointsFromStage(
  entries: BienDuLieuEntry[],
  stage: 1 | 2 | 3 | 4,
  batchStartMs: number,
): ChartPoint[] {
  const pts: ChartPoint[] = [];
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i];
    // Skip index-0 if it's a zero-init entry
    if (i === 0 && isInitEntry(e)) continue;
    const ts = parseTs(e.thoi_gian);
    if (!ts) continue;
    const phut = (ts.getTime() - batchStartMs) / 60000;
    if (phut < 0) continue;
    pts.push({ phut, value: e.nhiet_do ?? 0, stage });
  }
  return pts;
}

/** Build ChartPoint[] for ap_suat_chan_khong from a giai_doan bien_du_lieu array */
function buildApPointsFromStage(
  entries: BienDuLieuEntry[],
  stage: 1 | 2 | 3 | 4,
  batchStartMs: number,
): ChartPoint[] {
  const pts: ChartPoint[] = [];
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i];
    if (i === 0 && isInitEntry(e)) continue;
    const ts = parseTs(e.thoi_gian);
    if (!ts) continue;
    const phut = (ts.getTime() - batchStartMs) / 60000;
    if (phut < 0) continue;
    pts.push({ phut, value: e.ap_suat_chan_khong ?? 0, stage });
  }
  return pts;
}

/** The chart starts at the first recorded sample of stage 1, not document creation. */
function findBatchStartMs(doc: BatchDocument): number | null {
  const entries = doc.giai_doan_1?.bien_du_lieu ?? [];
  for (const entry of entries) {
    const ts = parseTs(entry.thoi_gian);
    if (ts) return ts.getTime();
  }
  return null;
}

function findLastRecordedStage(doc: BatchDocument): 1 | 2 | 3 | 4 | null {
  for (let g = 4 as 1 | 2 | 3 | 4; g >= 1; g--) {
    const gdKey = `giai_doan_${g}` as keyof BatchDocument;
    const gd = doc[gdKey] as { bien_du_lieu?: BienDuLieuEntry[] } | undefined;
    if (gd?.bien_du_lieu?.some((entry) => parseTs(entry.thoi_gian) !== null)) return g;
  }
  return null;
}

interface LoadedBatch {
  doc: BatchDocument;
  batchStartMs: number;
  running: boolean;
  lastStage: 1 | 2 | 3 | 4 | null;
}

/** Load the running batch, or the latest completed batch when the machine is idle. */
async function loadBatchHistory(
  n: number,
): Promise<LoadedBatch | null> {
  try {
    const list = await getNoiChien(n);
    if (!Array.isArray(list) || list.length === 0) return null;

    // API returns newest-first: forward scan for the first running batch; otherwise keep the newest (index 0).
    let selected = list[0];
    let running = false;
    for (let i = 0; i < list.length; i++) {
      if (list[i].thoi_gian_stop === '' || list[i].thoi_gian_stop == null) {
        selected = list[i];
        running = true;
        break;
      }
    }

    const doc = await getNoiChienDetail(selected._id, n);
    const fallbackStart = parseTs(selected.thoi_gian_start)?.getTime() ?? null;
    const batchStartMs = findBatchStartMs(doc) ?? fallbackStart;
    if (batchStartMs == null) return null;

    return { doc, batchStartMs, running, lastStage: findLastRecordedStage(doc) };
  } catch {
    return null;
  }
}

interface HistoryState {
  tempSeries: MachineSeries[];
  apSeries: MachineSeries[];
}

export function useFleetHistory(): HistoryState {
  const [state, setState] = useState<HistoryState>({ tempSeries: [], apSeries: [] });

  // Per-machine refs for batch start time and current series points
  const batchStartRef = useRef<Record<number, number>>({}); // n -> ms
  const batchRunningRef = useRef<Record<number, boolean>>({});
  const lastStageRef = useRef<Record<number, 1 | 2 | 3 | 4 | null>>({});
  const revisionRef = useRef<Record<number, number>>({});
  const tempPtsRef = useRef<Record<number, ChartPoint[]>>({}); // n -> ChartPoint[]
  const apPtsRef = useRef<Record<number, ChartPoint[]>>({});  // n -> ChartPoint[]

  /** Rebuild React state from refs (called after any mutation) */
  const pushState = () => {
    const tempSeries: MachineSeries[] = [];
    const apSeries: MachineSeries[] = [];
    for (let n = 1; n <= 8; n++) {
      const tPts = tempPtsRef.current[n];
      const aPts = apPtsRef.current[n];
      if (tPts && tPts.length > 0) {
        tempSeries.push({ n, color: FRYER_CHART_COLORS[n], points: [...tPts] });
      }
      if (aPts && aPts.length > 0) {
        apSeries.push({ n, color: FRYER_CHART_COLORS[n], points: [...aPts] });
      }
    }
    setState({ tempSeries, apSeries });
  };

  useEffect(() => {
    const sockets: Socket[] = [];
    let cancelled = false;

    // Initial batch load for all 8 machines (parallel)
    const loadAll = async () => {
      const revisionsAtLoad = Array.from(
        { length: 8 },
        (_, i) => revisionRef.current[i + 1] ?? 0,
      );
      const results = await Promise.allSettled(
        Array.from({ length: 8 }, (_, i) => loadBatchHistory(i + 1)),
      );

      if (cancelled) return;

      results.forEach((res, i) => {
        const n = i + 1;
        if ((revisionRef.current[n] ?? 0) !== revisionsAtLoad[i]) return;

        if (res.status === 'fulfilled' && res.value) {
          const { doc, batchStartMs, running, lastStage } = res.value;
          batchStartRef.current[n] = batchStartMs;
          batchRunningRef.current[n] = running;
          lastStageRef.current[n] = lastStage;

          const tPts: ChartPoint[] = [];
          const aPts: ChartPoint[] = [];

          for (let g = 1 as 1 | 2 | 3 | 4; g <= 4; g++) {
            const gdKey = `giai_doan_${g}` as keyof BatchDocument;
            const gd = doc[gdKey] as { bien_du_lieu?: BienDuLieuEntry[] } | undefined;
            const entries = gd?.bien_du_lieu ?? [];
            tPts.push(...buildPointsFromStage(entries, g, batchStartMs));
            aPts.push(...buildApPointsFromStage(entries, g, batchStartMs));
          }

          tempPtsRef.current[n] = capPoints(tPts);
          apPtsRef.current[n] = capPoints(aPts);
        }
      });

      if (!cancelled) pushState();
    };

    loadAll();

    // Open 8 sockets for live appending
    for (let n = 1; n <= 8; n++) {
      const socket = io({ forceNew: true });
      sockets.push(socket);

      socket.on('connect', () => {
        socket.emit('join_noi', String(n));
      });

      const machineN = n; // capture

      const onData = (payload: StagePayload[] | NoiChienDataPayload) => {
        if (cancelled) return;
        let stages: StagePayload[];
        if (Array.isArray(payload)) {
          stages = payload;
        } else {
          stages = payload.stages;
        }
        if (!Array.isArray(stages) || stages.length === 0) return;

        const activeIdx = stages.findIndex((s) => s.active);
        if (activeIdx < 0) return; // no active stage = not running
        const stageNum = (activeIdx + 1) as 1 | 2 | 3 | 4;
        const activeStage = stages[activeIdx];
        const sensor = activeStage.data;
        const sensorTs = parseTs(sensor.thoi_gian);
        if (!sensorTs) return;

        const previousStage = lastStageRef.current[machineN];
        const startsNewBatch = stageNum === 1 && (
          !batchRunningRef.current[machineN]
          || (previousStage != null && previousStage > 1)
        );

        if (startsNewBatch) {
          revisionRef.current[machineN] = (revisionRef.current[machineN] ?? 0) + 1;
          batchStartRef.current[machineN] = sensorTs.getTime();
          batchRunningRef.current[machineN] = true;
          tempPtsRef.current[machineN] = [];
          apPtsRef.current[machineN] = [];
        }

        if (!batchRunningRef.current[machineN]) return;

        const batchStart = batchStartRef.current[machineN];
        if (batchStart == null) return;

        // Both values originate from backend locale strings, avoiding the
        // Docker UTC vs browser local-time offset that previously added 420 min.
        const nowPhut = (sensorTs.getTime() - batchStart) / 60000;
        if (nowPhut < 0) return;
        lastStageRef.current[machineN] = stageNum;

        // --- Temperature ---
        const tPts = tempPtsRef.current[machineN] ?? [];
        const lastTPt = tPts[tPts.length - 1];
        if (!lastTPt || nowPhut - lastTPt.phut >= MIN_PHUT_GAP) {
          const newTPt: ChartPoint = { phut: nowPhut, value: sensor.nhiet_do ?? 0, stage: stageNum };
          tempPtsRef.current[machineN] = capPoints([...tPts, newTPt]);
        }

        // --- Vacuum pressure ---
        const aPts = apPtsRef.current[machineN] ?? [];
        const lastAPt = aPts[aPts.length - 1];
        if (!lastAPt || nowPhut - lastAPt.phut >= MIN_PHUT_GAP) {
          const newAPt: ChartPoint = { phut: nowPhut, value: sensor.ap_suat_chan_khong ?? 0, stage: stageNum };
          apPtsRef.current[machineN] = capPoints([...aPts, newAPt]);
        }

        pushState();
      };

      const onStop = () => {
        if (cancelled) return;
        // Keep the completed chart visible. Stage 1 of the next batch resets it.
        batchRunningRef.current[machineN] = false;
        revisionRef.current[machineN] = (revisionRef.current[machineN] ?? 0) + 1;
      };

      socket.on(`noi_chien_${n}_data`, onData as (...args: unknown[]) => void);
      socket.on(`noi_chien_${n}_stop`, onStop);
    }

    return () => {
      cancelled = true;
      for (const s of sockets) s.disconnect();
    };
  }, []);

  return state;
}
